### PR TITLE
RATEST: Refactor the pages from automated test folder 

### PR DESCRIPTION
**Pull request by kdaud**
Goal:
Refactor the pages from automated test folder

### CODE REVIEW

**Comment by kdaud** [comment]
cc; @sherrif10

**Comment by sherrif10** [comment]
@kdaud  is there any big difference between test and helper ?

**Comment by sherrif10** [comment]
> Ideally these classes dwelling in that folder are not tests but rather helper classes which are extended by automated test classes through inheritance concept in order to implement their respective methods.

Thanks @kdaud, this is simply folder naming, there is no big deal dealing with inheritance staff.

**Comment by sherrif10** [comment]
However thats fine too since there is no any code change

**Comment by kdaud** [comment]
The right architecture should not have pages stored in src/test/java folder that is the reason why I refactored the pages out of the that folder; ie src/test/java should store test files.

**Comment by sherrif10** [comment]
i think that would add more change  when we write integration tests, that's we they kept them in a single folder src/test for better maintenance. after all all are simply automations, i would think that artchitecture suffices and for automations framework i have worked on with, they are using same approach

**Comment by kdaud** [comment]
@sherrif10 for better organisation of files and code-base, src/test/java should store test files and pages would be stored elsewhere. But if you feel that is how things should be then its ok  otherwise pages are not tests.

**Comment by sherrif10** [comment]
What am trying to mean is, there is no difference here, creating more folders will make things little complex for nothing, if we keep them easy it would suffice

**Pull request closed without merging**
