### PR TITLE
RATEST-10: Rename module packages and update readme file

### PR DESCRIPTION
**Pull request by kdaud**
Goal:
Rename packages and update the read me file

### CODE REVIEW

**Comment by kdaud** [comment]
@sherrif10 take a look at this PR!

**Review by sherrif10 — COMMENTED** [review]
LGTM  can we solve login test failure first

**Comment by kdaud** [comment]
> LGTM can we solve login test failure first

Sorry @sherrif10 that I merged before reading the message above very well after receiving the approval notification.

**Comment by kdaud** [comment]
Let me look into the failing build and will rise the PR soon!

**Pull request merged**
